name: Example

on:
  push:
    branches: [testing]

jobs:
  example:
    runs-on: ubuntu-latest
    steps:
      - name: Print
        run: echo "Hello World"
      - name: Debug
        run: echo "::debug::this is a debug message"